# Generated by Django 4.0.6 on 2022-07-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='ipca',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='irr',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='rate',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
