# Generated by Django 4.0.6 on 2022-07-11 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transactions_ipca_transactions_irr_transactions_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
