# Generated by Django 4.0.6 on 2022-07-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulations',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
