# Generated by Django 4.0.6 on 2022-07-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0002_alter_simulations_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulations',
            name='deadline',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='simulations',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
