# Generated by Django 4.0.6 on 2022-07-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_simulations_deadline_alter_simulations_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulations',
            name='cdi',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
